version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i # to install npm
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ./node_modules
      - run: npm i 
      - run: npm run test
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ./node_modules
      - run: npm i
      - run: npm audit
workflows:
  ci-pipeline-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
