version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.1.0
    steps:
      - checkout
      - run: npm i -g npm-upgrade # to install npm
      - run: npm install -g esw
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:18.1.0
    steps:
      - checkout
      - run: npm i -g npm-upgrade
      - run: npm install -g jest
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:18.1.0
    steps:
      - checkout
      - run: npm audit
workflows:
  ci-pipeline-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
